Patches petalinux with popcorn v5.2.21

diff --git a/tools/testing/selftests/net/run_afpackettests b/tools/testing/selftests/net/run_afpackettests
--- a/tools/testing/selftests/net/run_afpackettests
+++ b/tools/testing/selftests/net/run_afpackettests
@@ -21,16 +21,12 @@ fi
 echo "--------------------"
 echo "running psock_tpacket test"
 echo "--------------------"
-if [ -f /proc/kallsyms ]; then
-	./in_netns.sh ./psock_tpacket
-	if [ $? -ne 0 ]; then
-		echo "[FAIL]"
-		ret=1
-	else
-		echo "[PASS]"
-	fi
+./in_netns.sh ./psock_tpacket
+if [ $? -ne 0 ]; then
+	echo "[FAIL]"
+	ret=1
 else
-	echo "[SKIP] CONFIG_KALLSYMS not enabled"
+	echo "[PASS]"
 fi
 
 echo "--------------------"
